// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp73dPAd20AGur7uVM20e_hzOy4u8vPco',
    appId: '1:1083941675840:web:63160b5acab56641c390a5',
    messagingSenderId: '1083941675840',
    projectId: 'petprojectbookingapp',
    authDomain: 'petprojectbookingapp.firebaseapp.com',
    storageBucket: 'petprojectbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1pcOI3kfHMLw7GZop4rp11z_FPIh6qY',
    appId: '1:1083941675840:android:562a4689402a537dc390a5',
    messagingSenderId: '1083941675840',
    projectId: 'petprojectbookingapp',
    storageBucket: 'petprojectbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVRtQ8ZRA9a4YzX9UNvA-gxa6zgNQCDE',
    appId: '1:1083941675840:ios:c5a43d4663aaad4ec390a5',
    messagingSenderId: '1083941675840',
    projectId: 'petprojectbookingapp',
    storageBucket: 'petprojectbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.petprojectsbookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrVRtQ8ZRA9a4YzX9UNvA-gxa6zgNQCDE',
    appId: '1:1083941675840:ios:c5a43d4663aaad4ec390a5',
    messagingSenderId: '1083941675840',
    projectId: 'petprojectbookingapp',
    storageBucket: 'petprojectbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.petprojectsbookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp73dPAd20AGur7uVM20e_hzOy4u8vPco',
    appId: '1:1083941675840:web:05cd46a16b2947fbc390a5',
    messagingSenderId: '1083941675840',
    projectId: 'petprojectbookingapp',
    authDomain: 'petprojectbookingapp.firebaseapp.com',
    storageBucket: 'petprojectbookingapp.firebasestorage.app',
  );
}
